plugins {
    id 'java-library'
    id 'maven-publish'
    id 'eclipse'
    id 'idea'
    id 'net.neoforged.gradle.userdev' version '7.0.185'
}

version = mod_version
group = mod_group_id

base {
    archivesName = mod_id
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
    withSourcesJar()
}

runs {
    configureEach {
        workingDirectory project.layout.projectDirectory.dir('run').dir(name)
        modSource sourceSets.main
    }
    client {}
    server { argument '--nogui' }
    gameTestServer {
        modSource sourceSets.test
        def gameTestNamespaces = providers.gradleProperty('gameTestNamespaces').getOrNull()
        if (gameTestNamespaces != null) {
            systemProperty 'neoforge.enabledGameTestNamespaces', gameTestNamespaces
        }
        workingDirectory providers.gradleProperty('gameTestWorkingDirectory')
            .map { file(it) }
            .orElse(project.layout.projectDirectory.dir('run').dir('gameTestServer-clean'))
    }
}

repositories {
    mavenCentral()
    maven { url = 'https://maven.neoforged.net/releases' }
}

dependencies {
    implementation "net.neoforged:neoforge:${neo_version}"
    testImplementation platform('org.junit:junit-bom:5.10.2')
    testImplementation 'org.junit.jupiter:junit-jupiter'
}

tasks.named('test') {
    useJUnitPlatform()
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

tasks.withType(ProcessResources).configureEach {
    var properties = [
        mod_version: project.version,
        neo_version: neo_version,
        minecraft_version: minecraft_version,
        minecraft_version_range: minecraft_version_range,
        loader_version_range: loader_version_range,
        mod_id: mod_id,
        mod_name: mod_name,
        mod_group_id: mod_group_id
    ]
    inputs.properties(properties)
    filteringCharset = 'UTF-8'
    filesMatching('META-INF/neoforge.mods.toml') {
        expand(properties)
    }
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
        }
    }
}
