org.gradle.jvmargs=-Xmx3G -Dfile.encoding=UTF-8
org.gradle.daemon=false

mod_id=dynamicfood
mod_name=Dynamic Food
mod_group_id=com.jorjik.dynamicfood
mod_version=0.1.0
neo_version=21.1.249
minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
loader_version_range=[4,)

# Gradle plugin / workspace compatibility
java_version=21
